### ISSUE TITLE
依據選擇領域組合信件內容

### ISSUE THREAD

**Issue by shinglyu** [moztw/contribute-reply-letters#2]
@irvin 提到這個系統需要自動化，也許我可以幫上一點忙? 不過要釐清一下輸入輸出是什麼?

假設輸入是 google 表單的資料，我建議可以分幾個階段:
1. 手動 copy Google form 的一行，輸入到一個 python script or HTML+JS 頁面，輸出生成好的文字內容，手動貼到信裡面寄出
2. 利用 Google 表單 API，定時去撈新人留下的資料，產生信件內容，手動寄出
3. 接上某種 mail API，自動寄信

不知道我這樣理解有沒有錯? ping @irvin @bobchao

**Comment by irvin** [comment]
之前 mozilla.org/zh-TW/contribute 中，有個簡單的表格，可以讓我們填寫 email，選擇一個用戶感興趣的領域，然後會自動將對應說明發到該信箱。

現在這個系統被砍掉了，因此每個填寫參與表單的人，我們都需要手動發信給對方。
如此實在太沒效率，只好自行開發一個。

參考規格： https://github.com/moztw/contribute-reply-letters/wiki/自動寄信回覆系統規格

**Comment by irvin** [comment]
之前 mozilla.org/zh-TW/contribute 中，有個簡單的表格，可以讓我們填寫 email，選擇一個用戶感興趣的領域，然後會自動將對應說明發到該信箱。

現在這個系統被砍掉了，因此每個填寫參與表單的人，我們都需要手動發信給對方。
如此實在太沒效率，只好自行開發一個。

**Comment by shinglyu** [comment]
先隨便寫了一個寫死的 script https://github.com/shinglyu/contribute-reply-letters/blob/script/src/compose.py

等 #4, #5  完成就可以套套看

**Comment by irvin** [comment]
@shinglyu  #4, #5 都 close 了，試試？

**Comment by irvin** [comment]
把這個 task 先簡化成建立自動組信機制，close
