### ISSUE TITLE
接上 Google 表單

### ISSUE THREAD

**Issue by shinglyu** [moztw/contribute-reply-letters#8]
@irvin 請問有表單結果的範例嗎?

**Comment by irvin** [comment]
紙本表單的參考依據是先前 mozilla.org/contribute 的 form，他們拔掉了，[這邊有舊的備份](http://mozilla.com.tw/community/contribute/)。
但是他不能複選領域，所以沒法直接對應來用。

目前紙本表單長這樣：（找不到空白的）
![scannable_ _ _2016 8 29 _ 3_11_30](https://cloud.githubusercontent.com/assets/165936/18043554/3c19bc24-6dfb-11e6-9635-a5fde54d89e7.png)

**Comment by irvin** [comment]
[線上的舊表單](https://docs.google.com/forms/d/e/1FAIpQLSf9RUSmv9etoRSLJxCSa9ZkBxG8tp-ScJ8N6na6ZUj5KYJX0g/viewform?embedded=true&formkey=dDdDdUlyWWhQQTczelZZb1k5VjAwbnc6MQ)則是長這樣：

![2016-08-29 15 16 35](https://cloud.githubusercontent.com/assets/165936/18043618/9f729462-6dfb-11e6-83cc-09a38b63c8ef.png)

**Comment by irvin** [comment]
需要重開一個 Google Form 的線上表單來用～

**Comment by irvin** [comment]
#11 先 merge，我正在 local 測測看

**Comment by irvin** [comment]
wontfix now!
