### ISSUE TITLE
建立新版的人力線上表單

### ISSUE THREAD

**Issue by irvin** [moztw/contribute-reply-letters#9]
ref https://github.com/moztw/contribute-reply-letters/issues/8
需參考以下紙本表單欄位，建立對應的 Google Form

![scannable_ _ _2016 8 29 _ 3_11_30](https://cloud.githubusercontent.com/assets/165936/18043554/3c19bc24-6dfb-11e6-9635-a5fde54d89e7.png)

**Comment by shinglyu** [comment]
感覺如果是電子版 那個 gmail/yahoo可有可無 這樣表單可以簡單一點

**Comment by shinglyu** [comment]
BTW 這份有 word 檔之類的嗎？可以少打一點字XD

**Comment by irvin** [comment]
gmail/yahoo  > 同意
就是沒有電子檔所以才掃描上來XD

**Comment by irvin** [comment]
[Uploading contribute.lang…]()
我找到原文的來源了

**Comment by irvin** [comment]
[contribute.txt](https://github.com/moztw/contribute-reply-letters/files/443985/contribute.txt)
我找到原文的來源了，是先前 www.mozilla.org 的 .lang 檔

**Comment by Sea-n** [comment]
@shinglyu MozTW 是開放文化社群，可以的話請避免使用 MS 的封閉格式，以 ODF PDF 等格式代替
(歪樓

**Comment by shinglyu** [comment]
@Sea-n 我自己是都用 Markdown/LaTex/ODF 啦 不過乍看覺得這份很像 Word 排版的所以才這樣問XD

**Comment by weichichou** [comment]
哈囉大家！我把紙本內容先做成google form了：
https://goo.gl/forms/gZYf4CpxJR2WIGUy2

我也想把上面的圖片放上去，不知道要去哪裡下載呢？

**Comment by irvin** [comment]
@weichichou 表單作得很棒，能把 google form、跟對應的資料表的權限分享給我嗎 （ irvin @ mail.moztw.org ）
現在這些圖示散落各地，還真的沒有整理好的地方。我可以找找看，不過需要時間
（這邊有其中兩個： https://moztw.org/community/#project ）

**Comment by weichichou** [comment]
@irvin  這是可以編輯google form的共用連結: https://docs.google.com/forms/d/1jXyw6V4hThUM-pCjU5fHBrCCOCFIOuiQpbvWX11sZWc/edit?usp=sharing
請取用~~ :)

**Comment by irvin** [comment]
@weichichou 由於個資安全性的關係，我先把點入連結就可編輯的權限關掉了，感謝

**Comment by irvin** [comment]
@weichichou https://www.dropbox.com/sh/p7aao06kzvk8ulb/AABv4d572RvFA_EsrsMoaPhDa?dl=0 這邊是每個圖示的資料夾，有幾個我有換掉（編輯：更新網址）

**Comment by irvin** [comment]
@weichichou 填表完成後的那個 spreadsheet 也可以分享一下嗎？

**Comment by weichichou** [comment]
@irvin 共用連結點進去上方有「問題」和「回覆」兩個頁籤，「回覆」那裡面有個小圖示，可以把內容匯出成spreadsheet (你是編輯者，應該是看得到的)。
不過現在還沒有人填，所以是空白的~~

**Comment by irvin** [comment]
喔喔我找到建立試算表的功能了，先建起來 > https://docs.google.com/spreadsheets/d/1U41ouZnWU9Vnw-h9_4UQdxMy3f5jBhf48He1Sw6dxi4/edit?usp=sharing

我昨天試了一下，結果沒有按到最後的送出按鈕

@shinglyu 這樣你可以接上寄信嗎？

**Comment by irvin** [comment]
Orz 選項好像被我剛剛改壞了，我先把備份倒回來

**Comment by irvin** [comment]
幾個修改：
1. 人力處改成一個問題一個選項，讓後面接上發信程式時方便
2. 改成兩個區段，因為我發現到第三個區段會讓人誤以為已經送出
3. 修改一些文案細節
4. 加入其他與發問選項

@shinglyu 你可以試試看從 spreadsheets 接上寄信的程式？

**Comment by shinglyu** [comment]
@irvin Sorry 上個禮拜都在出差 下個禮拜還要出差QAQ 我空檔盡快弄一弄

**Comment by irvin** [comment]
感謝 @weichichou 我複製一份表單到下面，close 這個 task
表單  https://goo.gl/forms/z8CC4AmWXRGANTdh2
結果資料  https://docs.google.com/spreadsheets/d/19CMUqMa_spjIFem_qHcUwompkFrAOeDI4uTrZLBXaNM/edit?usp=sharing
